# Generated by Django 5.1.5 on 2025-09-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ruta',
            name='fecha',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
