# Generated by Django 5.1.5 on 2025-09-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0002_alter_ruta_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='sport',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
