# Generated by Django 5.1.5 on 2025-10-09 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0003_ruta_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='imagen',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
