# Generated by Django 5.1.5 on 2025-10-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0004_ruta_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='ruta',
            name='puntos',
            field=models.JSONField(default=list),
        ),
    ]
