# Generated by Django 5.1.5 on 2025-10-24 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0005_ruta_puntos'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ruta',
            new_name='Activity',
        ),
    ]
