# Generated by Django 5.1.5 on 2025-12-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0006_rename_ruta_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
