# Generated by Django 5.1.5 on 2025-12-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0007_activity_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ubicacion',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
