# Generated by Django 5.1.5 on 2025-12-20 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0008_alter_activity_ubicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='distancia',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='tiempo',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
