# Generated by Django 5.1.5 on 2025-12-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0009_activity_distancia_activity_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fc_med',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='ritmo',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='subida',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
