# Generated by Django 5.1.5 on 2025-12-21 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0010_activity_fc_med_activity_ritmo_activity_subida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='ritmo',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
