# Generated by Django 5.1.5 on 2025-12-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mapas', '0011_alter_activity_ritmo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='altura',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_z1',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_z2',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_z3',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='card_z4',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='edad',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fc_max',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fc_reposo',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='peso',
            field=models.FloatField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
